{% load data_capture %}

Hi [username],

We're emailing regarding the Region 10 CALC data upload #{{ upload_source.id }},
uploaded by {{ upload_source.submitter.email }} on {{ upload_source.created_at|tz_timestamp }}.

Unfortunately, an error occurred while importing the data.
The traceback below may help the development team debug the problem.

{{ traceback }}

If you have any questions, let us know.

Thanks,

The CALC team
